'use strict';

(() => {
  const en = {
    pageTitle: 'YouTube Toolkit guide', brandAria: 'YouTube Toolkit guide home', skipTour: 'Skip guide', closeAria: 'Close guide',
    stepLabel: 'Step {current} of {total}', goToStep: 'Go to step {step}: {name}', back: 'Back', next: 'Next', finish: 'Finish', openYouTube: 'Open YouTube', progressAria: 'Guide progress', closePrompt: 'Would you like to close the guide?', yes: 'Yes', no: 'No',
    practiceLabel: 'Try it', autoHint: 'Loops whenever idle', demoVideo: 'DEMO VIDEO', holdHere: 'HOLD LEFT-CLICK HERE',
    volumeTitle: 'Volume Drag', volumeHeading: 'Drag sideways to change the volume.', volumeAria: 'Practise horizontal volume dragging',
    volumeStatusWatch: 'Watch the pointer, then drag left or right on the demo.',
    volumeInstruction1: 'Hold left-click on the video and drag sideways.',
    volumeInstruction2: 'Hold Alt to drag from anywhere on YouTube.',
    volumeInstruction3: 'Change the button and sensitivity in the extension.',
    volumeTry: 'Try it: drag left or right on the demo, or use the arrow keys.', volumeWatch: 'Watch the pointer drag right to raise the volume.', volumeYourTurn: 'Your turn: hold and drag anywhere on the demo.', volumeHolding: 'Keep holding and move left or right.', volumeSet: 'Nice — you set the demo volume to {volume}%.', volumeValue: 'Demo volume: {volume}%.', muted: 'Muted',
    layoutTitle: 'Layout Trimmer', layoutHeading: 'Make wide screens easier to watch.', layoutBody: 'Adjust the page width and suggested-video width together until the layout feels balanced.', narrower: 'Narrower', wider: 'Wider', toggle: 'Toggle',
    skipTitle: 'SkipIt', skipHeading: "One skip can trigger YouTube's Jump ahead.", or: 'or', jumpAhead: 'Jump ahead',
    skipInstruction1: 'Press Right Arrow or L once when YouTube offers its Jump ahead action.', skipInstruction2: 'SkipIt waits for your chosen delay, then activates the visible action.', skipInstruction3: 'Press the skip key again during the delay to cancel the automatic jump.',
    speedTitle: 'Speed Lock', speedHeading: 'Hold, choose a speed, and let go.', speedAria: 'Practise holding the video, moving to a speed pill, and releasing', speedStatusWatch: 'Watch: hold the video, move to the 2x pill, then release.',
    speedInstruction1: 'Hold left-click on the video.', speedInstruction2: 'Move onto a speed pill and release.', speedInstruction3: 'Hold a little longer to show 0.25x steps.',
    speedTry: 'Try it: hold the demo, move onto a speed pill, then release.', speedHoldWatch: 'Hold the left mouse button on the video.', speedPillAppears: 'The 2x pill appears. Move onto it.', speedReleaseLock: 'Release over the pill to lock 2x.', speedYourTurn: 'Your turn: hold the demo, move to a pill, and release.', speedHolding: 'Keep holding, then move onto the 2x pill.', speedOpen: 'Extra speeds are open. Release over any pill.', speedReleaseRate: 'Release to lock {rate}x.', speedSuccess: 'Success — {rate}x is locked.', speedAlmost: 'Almost — release while the pointer is over a speed pill.', speedTryAgain: 'Try again: hold, move to a pill, then release.',
    headphoneTitle: 'Headphone shortcut', headphoneHeading: 'Pause, then resume to trigger SkipIt.', headphoneLead: 'Use pause and play within your chosen threshold to automatically skip commonly skipped sections.', animatedExample: 'Animated example', headphoneAnimationAria: 'A side-view hand double-tapping the right earcup of a pair of headphones', playing: 'Playing', paused: 'Paused', skipped: 'Skipped',
    headphonePauseStep: 'Double-tap the earcup to pause the video.', headphoneResumeStep: 'Double-tap again within your chosen time to resume.', headphoneDeviceNote: 'Works with headphones, earbuds, remotes, keyboards, and any other device that can pause and resume the video.',
    readyTitle: 'Ready', readyHeading: 'More options and settings are available.', moreSettingsTitle: 'Head to YouTube Toolkit', readyBody: 'Change your settings, customise every feature, or replay this guide whenever you like.', finishSettingsHint: 'Select Finish to open it now.'
  };

  const translations = {
    es: {
      pageTitle: 'Guía de YouTube Toolkit', brandAria: 'Inicio de la guía de YouTube Toolkit', skipTour: 'Omitir guía', closeAria: 'Cerrar guía', stepLabel: 'Paso {current} de {total}', goToStep: 'Ir al paso {step}: {name}', back: 'Atrás', next: 'Siguiente', finish: 'Terminar', openYouTube: 'Abrir YouTube', progressAria: 'Progreso de la guía', closePrompt: '¿Quieres cerrar la guía?', yes: 'Sí', no: 'No',
      practiceLabel: 'Práctica interactiva', autoHint: 'Se repite cuando está inactivo', demoVideo: 'VÍDEO DE PRUEBA', holdHere: 'MANTÉN PULSADO AQUÍ',
      volumeTitle: 'Volumen al arrastrar', volumeHeading: 'Arrastra hacia los lados para cambiar el volumen.', volumeAria: 'Practica el control horizontal del volumen', volumeStatusWatch: 'Mira el puntero y luego arrastra a izquierda o derecha.',
      volumeInstruction1: 'Mantén pulsado el botón izquierdo sobre un vídeo y mueve el ratón hacia un lado. Un pequeño movimiento activa el volumen; si no te mueves, se mantiene el gesto normal de 2x de YouTube.', volumeInstruction2: 'Para arrastrar desde cualquier parte de YouTube, mantén Alt pulsado.', volumeInstruction3: 'Abre la extensión para cambiar el botón del ratón, la sensibilidad y el indicador de volumen.',
      volumeTry: 'Pruébalo: arrastra a izquierda o derecha, o usa las flechas.', volumeWatch: 'Mira cómo el puntero se mueve a la derecha y sube el volumen.', volumeYourTurn: 'Tu turno: mantén pulsado y arrastra en la demostración.', volumeHolding: 'Sigue pulsando y mueve a izquierda o derecha.', volumeSet: 'Bien: has ajustado el volumen al {volume}%.', volumeValue: 'Volumen de prueba: {volume}%.', muted: 'Silenciado',
      layoutTitle: 'Ajuste del diseño', layoutHeading: 'Haz más cómodas las pantallas anchas.', layoutBody: 'Ajusta juntos el ancho de la página y el de los vídeos sugeridos hasta equilibrar el diseño.', narrower: 'Más estrecho', wider: 'Más ancho', toggle: 'Activar',
      skipTitle: 'SkipIt', skipHeading: 'Un salto puede activar Avanzar de YouTube.', or: 'o', jumpAhead: 'Avanzar', skipInstruction1: 'Pulsa una vez Flecha derecha o L cuando YouTube ofrezca Avanzar.', skipInstruction2: 'SkipIt espera el tiempo elegido y activa la acción visible.', skipInstruction3: 'Pulsa de nuevo la tecla durante la espera para cancelar.',
      speedTitle: 'Bloqueo de velocidad', speedHeading: 'Mantén pulsado, elige una velocidad y suelta.', speedAria: 'Practica cómo mantener pulsado, elegir una velocidad y soltar', speedStatusWatch: 'Mira: mantén pulsado, ve a 2x y suelta.', speedInstruction1: 'Mantén pulsado el botón izquierdo sobre el vídeo hasta que aparezca la velocidad.', speedInstruction2: 'Mueve el puntero a una opción y suelta para fijarla. Repite para volver a 1x.', speedInstruction3: 'Mantén pulsado un momento para mostrar velocidades cercanas en pasos de 0,25x.',
      speedTry: 'Pruébalo: mantén pulsado, elige una velocidad y suelta.', speedHoldWatch: 'Mantén pulsado el botón izquierdo sobre el vídeo.', speedPillAppears: 'Aparece 2x. Mueve el puntero encima.', speedReleaseLock: 'Suelta sobre la opción para fijar 2x.', speedYourTurn: 'Tu turno: mantén pulsado, elige una velocidad y suelta.', speedHolding: 'Sigue pulsando y mueve el puntero a 2x.', speedOpen: 'Ya están disponibles más velocidades. Suelta sobre una.', speedReleaseRate: 'Suelta para fijar {rate}x.', speedSuccess: 'Listo: se ha fijado {rate}x.', speedAlmost: 'Casi: suelta con el puntero sobre una velocidad.', speedTryAgain: 'Inténtalo de nuevo: mantén pulsado, mueve y suelta.',
      headphoneTitle: 'Atajo con auriculares', headphoneHeading: 'Pausa y reanuda para activar SkipIt.', headphoneLead: 'Usa pausa y reproducción dentro del umbral elegido para saltar automáticamente las secciones que suelen omitirse.', animatedExample: 'Ejemplo animado', headphoneAnimationAria: 'Una mano de perfil toca dos veces el auricular derecho de unos auriculares', playing: 'Reproduciendo', paused: 'En pausa', skipped: 'Omitido', headphonePauseStep: 'Toca dos veces el auricular para pausar el vídeo.', headphoneResumeStep: 'Toca dos veces de nuevo dentro del tiempo elegido para reanudar.', headphoneDeviceNote: 'Funciona con auriculares, audífonos, mandos, teclados y cualquier otro dispositivo que pueda pausar y reanudar el vídeo.',
      readyTitle: 'Listo', readyHeading: 'Hay más opciones y ajustes disponibles.', moreSettingsTitle: 'Abre YouTube Toolkit', readyBody: 'Cambia tus ajustes, personaliza cada función o vuelve a abrir esta guía cuando quieras.', finishSettingsHint: 'Selecciona Terminar para abrirlo ahora.'
    },
    fr: {
      pageTitle: 'Guide YouTube Toolkit', brandAria: 'Accueil du guide YouTube Toolkit', skipTour: 'Ignorer le guide', closeAria: 'Fermer le guide', stepLabel: 'Étape {current} sur {total}', goToStep: 'Aller à l’étape {step} : {name}', back: 'Retour', next: 'Suivant', finish: 'Terminer', openYouTube: 'Ouvrir YouTube', progressAria: 'Progression du guide', closePrompt: 'Voulez-vous fermer le guide ?', yes: 'Oui', no: 'Non',
      practiceLabel: 'Exercice interactif', autoHint: 'Se répète pendant l’inactivité', demoVideo: 'VIDÉO DE DÉMO', holdHere: 'MAINTENEZ LE CLIC ICI',
      volumeTitle: 'Volume par glissement', volumeHeading: 'Glissez horizontalement pour régler le volume.', volumeAria: 'S’exercer au réglage horizontal du volume', volumeStatusWatch: 'Regardez le pointeur, puis glissez à gauche ou à droite.', volumeInstruction1: 'Maintenez le bouton gauche sur une vidéo et déplacez la souris horizontalement. Un petit mouvement règle le volume ; sans mouvement, le geste 2x normal de YouTube reste actif.', volumeInstruction2: 'Pour glisser n’importe où sur YouTube, maintenez Alt.', volumeInstruction3: 'Ouvrez l’extension pour modifier le bouton, la sensibilité et l’affichage du volume.',
      volumeTry: 'Essayez : glissez à gauche ou à droite, ou utilisez les flèches.', volumeWatch: 'Regardez le pointeur aller à droite pour augmenter le volume.', volumeYourTurn: 'À vous : maintenez et glissez sur la démo.', volumeHolding: 'Maintenez le clic et déplacez-vous à gauche ou à droite.', volumeSet: 'Bien — volume réglé à {volume} %.', volumeValue: 'Volume de démo : {volume} %.', muted: 'Muet',
      layoutTitle: 'Ajustement de la page', layoutHeading: 'Rendez les écrans larges plus confortables.', layoutBody: 'Ajustez ensemble la largeur de la page et celle des suggestions jusqu’à obtenir un bon équilibre.', narrower: 'Plus étroit', wider: 'Plus large', toggle: 'Activer',
      skipTitle: 'SkipIt', skipHeading: 'Un saut peut déclencher l’avance de YouTube.', or: 'ou', jumpAhead: 'Avancer', skipInstruction1: 'Appuyez une fois sur Flèche droite ou L lorsque YouTube propose d’avancer.', skipInstruction2: 'SkipIt attend le délai choisi, puis active l’action visible.', skipInstruction3: 'Appuyez à nouveau pendant le délai pour annuler.',
      speedTitle: 'Verrouillage de vitesse', speedHeading: 'Maintenez, choisissez une vitesse, puis relâchez.', speedAria: 'S’exercer à maintenir, choisir une vitesse et relâcher', speedStatusWatch: 'Regardez : maintenez la vidéo, allez sur 2x, puis relâchez.', speedInstruction1: 'Maintenez le bouton gauche sur la vidéo jusqu’à l’apparition de la vitesse.', speedInstruction2: 'Placez-vous sur une vitesse et relâchez pour la verrouiller. Recommencez pour revenir à 1x.', speedInstruction3: 'Maintenez un instant pour afficher les vitesses proches par pas de 0,25x.',
      speedTry: 'Essayez : maintenez, allez sur une vitesse, puis relâchez.', speedHoldWatch: 'Maintenez le bouton gauche sur la vidéo.', speedPillAppears: 'Le bouton 2x apparaît. Placez le pointeur dessus.', speedReleaseLock: 'Relâchez sur le bouton pour verrouiller 2x.', speedYourTurn: 'À vous : maintenez, choisissez une vitesse et relâchez.', speedHolding: 'Maintenez et placez le pointeur sur 2x.', speedOpen: 'Les autres vitesses sont visibles. Relâchez sur l’une d’elles.', speedReleaseRate: 'Relâchez pour verrouiller {rate}x.', speedSuccess: 'Réussi — {rate}x est verrouillé.', speedAlmost: 'Presque — relâchez avec le pointeur sur une vitesse.', speedTryAgain: 'Réessayez : maintenez, déplacez, puis relâchez.',
      headphoneTitle: 'Raccourci casque', headphoneHeading: 'Mettez en pause, puis reprenez pour déclencher SkipIt.', headphoneLead: 'Utilisez pause et lecture dans le délai choisi pour ignorer automatiquement les sections souvent passées.', animatedExample: 'Exemple animé', headphoneAnimationAria: 'Une main vue de côté touche deux fois l’écouteur droit d’un casque', playing: 'Lecture', paused: 'En pause', skipped: 'Passé', headphonePauseStep: 'Touchez deux fois l’écouteur pour mettre la vidéo en pause.', headphoneResumeStep: 'Touchez à nouveau deux fois dans le délai choisi pour reprendre.', headphoneDeviceNote: 'Fonctionne avec les casques, écouteurs, télécommandes, claviers et tout autre appareil pouvant mettre la vidéo en pause et la reprendre.',
      readyTitle: 'Prêt', readyHeading: 'D’autres options et réglages sont disponibles.', moreSettingsTitle: 'Ouvrez YouTube Toolkit', readyBody: 'Modifiez vos réglages, personnalisez chaque fonction ou relancez ce guide à tout moment.', finishSettingsHint: 'Sélectionnez Terminer pour l’ouvrir maintenant.'
    },
    de: {
      pageTitle: 'YouTube Toolkit Anleitung', brandAria: 'Start der YouTube Toolkit Anleitung', skipTour: 'Anleitung überspringen', closeAria: 'Anleitung schließen', stepLabel: 'Schritt {current} von {total}', goToStep: 'Zu Schritt {step}: {name}', back: 'Zurück', next: 'Weiter', finish: 'Fertig', openYouTube: 'YouTube öffnen', progressAria: 'Fortschritt der Anleitung', closePrompt: 'Möchtest du die Anleitung schließen?', yes: 'Ja', no: 'Nein', practiceLabel: 'Interaktiv ausprobieren', autoHint: 'Wiederholt sich bei Inaktivität', demoVideo: 'DEMOVIDEO', holdHere: 'LINKE MAUSTASTE HIER HALTEN',
      volumeTitle: 'Lautstärke ziehen', volumeHeading: 'Seitwärts ziehen, um die Lautstärke zu ändern.', volumeAria: 'Horizontale Lautstärkeregelung ausprobieren', volumeStatusWatch: 'Beobachte den Zeiger und ziehe dann nach links oder rechts.', volumeInstruction1: 'Halte die linke Maustaste auf einem Video und bewege die Maus seitwärts. Eine kleine Bewegung regelt die Lautstärke; ohne Bewegung bleibt YouTubes normale 2x-Geste erhalten.', volumeInstruction2: 'Halte Alt gedrückt, um überall auf YouTube zu ziehen.', volumeInstruction3: 'Öffne die Erweiterung, um Maustaste, Empfindlichkeit und Lautstärkeanzeige zu ändern.', volumeTry: 'Probiere es: Ziehe nach links oder rechts oder nutze die Pfeiltasten.', volumeWatch: 'Der Zeiger zieht nach rechts und erhöht die Lautstärke.', volumeYourTurn: 'Jetzt du: Halten und auf der Demo ziehen.', volumeHolding: 'Gedrückt halten und nach links oder rechts bewegen.', volumeSet: 'Gut — Demolautstärke auf {volume} % gesetzt.', volumeValue: 'Demolautstärke: {volume} %.', muted: 'Stumm',
      layoutTitle: 'Layout anpassen', layoutHeading: 'Breite Bildschirme angenehmer nutzen.', layoutBody: 'Passe Seitenbreite und Vorschlagsbreite gemeinsam an, bis das Layout ausgewogen wirkt.', narrower: 'Schmaler', wider: 'Breiter', toggle: 'Umschalten', skipTitle: 'SkipIt', skipHeading: 'Ein Sprung kann YouTubes Vorspulen auslösen.', or: 'oder', jumpAhead: 'Vorspulen', skipInstruction1: 'Drücke einmal Pfeil rechts oder L, wenn YouTube Vorspulen anbietet.', skipInstruction2: 'SkipIt wartet die gewählte Zeit und aktiviert dann die sichtbare Aktion.', skipInstruction3: 'Drücke während der Wartezeit erneut, um abzubrechen.',
      speedTitle: 'Tempo sperren', speedHeading: 'Halten, Tempo wählen und loslassen.', speedAria: 'Halten, Tempo auswählen und Loslassen ausprobieren', speedStatusWatch: 'Beobachte: Video halten, auf 2x bewegen und loslassen.', speedInstruction1: 'Halte die linke Maustaste auf dem Video, bis die Tempoauswahl erscheint.', speedInstruction2: 'Bewege den Zeiger auf ein Tempo und lasse los. Wiederhole dies für 1x.', speedInstruction3: 'Halte kurz länger, um benachbarte Tempi in 0,25x-Schritten zu sehen.', speedTry: 'Probiere es: Halten, Tempo wählen und loslassen.', speedHoldWatch: 'Halte die linke Maustaste auf dem Video.', speedPillAppears: '2x erscheint. Bewege den Zeiger darauf.', speedReleaseLock: 'Über 2x loslassen, um es zu sperren.', speedYourTurn: 'Jetzt du: Halten, Tempo wählen und loslassen.', speedHolding: 'Weiter halten und den Zeiger auf 2x bewegen.', speedOpen: 'Weitere Tempi sind sichtbar. Über einem davon loslassen.', speedReleaseRate: 'Loslassen, um {rate}x zu sperren.', speedSuccess: 'Geschafft — {rate}x ist gesperrt.', speedAlmost: 'Fast — mit dem Zeiger über einem Tempo loslassen.', speedTryAgain: 'Noch einmal: Halten, bewegen und loslassen.',
      headphoneTitle: 'Kopfhörer-Kürzel', headphoneHeading: 'Pausieren und fortsetzen, um SkipIt auszulösen.', headphoneLead: 'Nutze Pause und Wiedergabe innerhalb des gewählten Zeitfensters, um häufig übersprungene Abschnitte automatisch zu überspringen.', animatedExample: 'Animiertes Beispiel', headphoneAnimationAria: 'Eine Hand von der Seite tippt zweimal auf die rechte Ohrmuschel eines Kopfhörers', playing: 'Wiedergabe', paused: 'Pausiert', skipped: 'Übersprungen', headphonePauseStep: 'Tippe zweimal auf die Ohrmuschel, um das Video zu pausieren.', headphoneResumeStep: 'Tippe innerhalb der gewählten Zeit erneut zweimal, um fortzusetzen.', headphoneDeviceNote: 'Funktioniert mit Kopfhörern, Ohrhörern, Fernbedienungen, Tastaturen und jedem anderen Gerät, das das Video pausieren und fortsetzen kann.',
      readyTitle: 'Fertig', readyHeading: 'Weitere Optionen und Einstellungen sind verfügbar.', moreSettingsTitle: 'Öffne YouTube Toolkit', readyBody: 'Ändere Einstellungen, passe jede Funktion an oder öffne diese Anleitung jederzeit erneut.', finishSettingsHint: 'Wähle Fertig, um es jetzt zu öffnen.'
    },
    pt: {
      pageTitle: 'Guia do YouTube Toolkit', brandAria: 'Início do guia do YouTube Toolkit', skipTour: 'Ignorar guia', closeAria: 'Fechar guia', stepLabel: 'Passo {current} de {total}', goToStep: 'Ir para o passo {step}: {name}', back: 'Voltar', next: 'Seguinte', finish: 'Concluir', openYouTube: 'Abrir YouTube', progressAria: 'Progresso do guia', closePrompt: 'Gostaria de fechar o guia?', yes: 'Sim', no: 'Não', practiceLabel: 'Prática interativa', autoHint: 'Repete quando está inativo', demoVideo: 'VÍDEO DE DEMONSTRAÇÃO', holdHere: 'MANTENHA O CLIQUE AQUI',
      volumeTitle: 'Volume ao arrastar', volumeHeading: 'Arraste para os lados para alterar o volume.', volumeAria: 'Praticar o controlo horizontal do volume', volumeStatusWatch: 'Veja o ponteiro e arraste para a esquerda ou direita.', volumeInstruction1: 'Mantenha o botão esquerdo premido num vídeo e mova para o lado. Um pequeno movimento controla o volume; sem mover, o gesto normal de 2x do YouTube continua disponível.', volumeInstruction2: 'Para arrastar em qualquer parte do YouTube, mantenha Alt premido.', volumeInstruction3: 'Abra a extensão para alterar o botão, a sensibilidade e o indicador de volume.', volumeTry: 'Experimente: arraste para a esquerda ou direita, ou use as setas.', volumeWatch: 'Veja o ponteiro mover-se para a direita e aumentar o volume.', volumeYourTurn: 'Agora experimente: mantenha premido e arraste na demonstração.', volumeHolding: 'Continue a premir e mova para a esquerda ou direita.', volumeSet: 'Boa — definiu o volume para {volume}%.', volumeValue: 'Volume de demonstração: {volume}%.', muted: 'Sem som',
      layoutTitle: 'Ajuste do esquema', layoutHeading: 'Torne os ecrãs largos mais confortáveis.', layoutBody: 'Ajuste em conjunto a largura da página e dos vídeos sugeridos até o esquema ficar equilibrado.', narrower: 'Mais estreito', wider: 'Mais largo', toggle: 'Alternar', skipTitle: 'SkipIt', skipHeading: 'Um salto pode acionar o Avançar do YouTube.', or: 'ou', jumpAhead: 'Avançar', skipInstruction1: 'Prima Seta direita ou L uma vez quando o YouTube oferecer Avançar.', skipInstruction2: 'O SkipIt aguarda o atraso escolhido e ativa a ação visível.', skipInstruction3: 'Prima novamente durante a espera para cancelar.',
      speedTitle: 'Bloqueio de velocidade', speedHeading: 'Mantenha, escolha a velocidade e solte.', speedAria: 'Praticar manter premido, escolher uma velocidade e soltar', speedStatusWatch: 'Veja: mantenha o vídeo premido, mova para 2x e solte.', speedInstruction1: 'Mantenha o botão esquerdo premido no vídeo até aparecer a velocidade.', speedInstruction2: 'Mova para uma velocidade e solte para a bloquear. Repita para voltar a 1x.', speedInstruction3: 'Continue a premir por um momento para mostrar velocidades em passos de 0,25x.', speedTry: 'Experimente: mantenha premido, escolha uma velocidade e solte.', speedHoldWatch: 'Mantenha o botão esquerdo premido no vídeo.', speedPillAppears: 'A opção 2x aparece. Mova o ponteiro para ela.', speedReleaseLock: 'Solte sobre a opção para bloquear 2x.', speedYourTurn: 'Agora experimente: mantenha, escolha e solte.', speedHolding: 'Continue a premir e mova para 2x.', speedOpen: 'As velocidades adicionais estão abertas. Solte sobre uma.', speedReleaseRate: 'Solte para bloquear {rate}x.', speedSuccess: 'Sucesso — {rate}x está bloqueado.', speedAlmost: 'Quase — solte com o ponteiro sobre uma velocidade.', speedTryAgain: 'Tente novamente: mantenha, mova e solte.',
      headphoneTitle: 'Atalho dos auscultadores', headphoneHeading: 'Pause e retome para acionar o SkipIt.', headphoneLead: 'Use pausa e reprodução dentro do limite escolhido para saltar automaticamente secções que costumam ser ignoradas.', animatedExample: 'Exemplo animado', headphoneAnimationAria: 'Uma mão vista de lado toca duas vezes no auscultador direito de uns auscultadores', playing: 'A reproduzir', paused: 'Em pausa', skipped: 'Avançado', headphonePauseStep: 'Toque duas vezes no auscultador para pausar o vídeo.', headphoneResumeStep: 'Toque novamente duas vezes dentro do tempo escolhido para retomar.', headphoneDeviceNote: 'Funciona com auscultadores, auriculares, comandos, teclados e qualquer outro dispositivo que possa pausar e retomar o vídeo.',
      readyTitle: 'Pronto', readyHeading: 'Existem mais opções e definições disponíveis.', moreSettingsTitle: 'Abra o YouTube Toolkit', readyBody: 'Altere as definições, personalize cada funcionalidade ou volte a abrir este guia quando quiser.', finishSettingsHint: 'Selecione Concluir para abrir agora.'
    }
  };

  const browserLanguage = (globalThis.chrome?.i18n?.getUILanguage?.() || navigator.language || 'en').replace('_', '-');
  const languageKey = browserLanguage.toLowerCase().split('-')[0];
  const messages = { ...en, ...(translations[languageKey] || {}) };

  function t(key, values = {}) {
    const template = messages[key] || en[key] || key;
    return template.replace(/\{(\w+)\}/g, (match, name) => values[name] ?? match);
  }

  function localize(root = document) {
    document.documentElement.lang = translations[languageKey] ? browserLanguage : 'en';
    document.title = t('pageTitle');
    root.querySelectorAll('[data-i18n]').forEach((element) => {
      element.textContent = t(element.dataset.i18n);
    });
    root.querySelectorAll('[data-i18n-aria-label]').forEach((element) => {
      element.setAttribute('aria-label', t(element.dataset.i18nAriaLabel));
    });
  }

  globalThis.OnboardingI18n = { t, localize, language: languageKey };
})();
